---
deployment:
  tasks:
    - export DEPLOYPATH=/home/username/public_html
    - /bin/cp -R * $DEPLOYPATH/
    - /bin/cp -R .[^.]* $DEPLOYPATH/ 2>/dev/null || true
    - cd $DEPLOYPATH
    - /usr/local/bin/php /usr/local/bin/composer install --no-dev --optimize-autoloader
    - /usr/local/bin/npm install
    - /usr/local/bin/npm run build
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache
    - /usr/local/bin/php artisan storage:link
    # Jalankan migrations hanya jika database dikonfigurasi (opsional)
    # Uncomment baris di bawah jika menggunakan database:
    # - /usr/local/bin/php artisan migrate --force
    - /bin/chmod -R 755 storage bootstrap/cache
    - /bin/chmod -R 755 $DEPLOYPATH/storage $DEPLOYPATH/bootstrap/cache

